export const mockInfluencers = [
  {
    id: "inf_1",
    name: "Sophie Martin",
    bio: "Passionnée de mode et lifestyle parisien. Créatrice de contenu depuis 5 ans.",
    photo: "https://i.pravatar.cc/300?img=47",
    instagram: "@sophiemartin",
    tiktok: "@sophiemartin",
    youtube: "SophieMartin",
    followers: 85000,
    engagementRate: 4.2,
    category: "MACRO",
    interests: ["Mode", "Lifestyle", "Beauté"],
    gender: "Femme",
    country: "France",
    languages: ["Français", "Anglais"],
    ratePost: 800,
    rateStory: 200,
    rateVideo: 1500,
    isVerified: true,
    isActive: true,
    subscription: "PRO",
    balance: 2450,
    userId: "user_inf_1",
  },
  {
    id: "inf_2",
    name: "Lucas Dubois",
    bio: "Créateur de contenu fitness & nutrition. Coach certifié.",
    photo: "https://i.pravatar.cc/300?img=11",
    instagram: "@lucasdubois_fit",
    tiktok: "@lucasdubois",
    followers: 145000,
    engagementRate: 5.8,
    category: "MACRO",
    interests: ["Fitness", "Nutrition", "Sport"],
    gender: "Homme",
    country: "France",
    languages: ["Français"],
    ratePost: 1200,
    rateStory: 350,
    rateVideo: 2500,
    isVerified: true,
    isActive: true,
    subscription: "PRO",
    balance: 5800,
    userId: "user_inf_2",
  },
  {
    id: "inf_3",
    name: "Emma Laurent",
    bio: "Influenceuse voyage et gastronomie. J'explore le monde pour vous.",
    photo: "https://i.pravatar.cc/300?img=32",
    instagram: "@emmalaurent_travel",
    youtube: "EmmaLaurentTravel",
    followers: 320000,
    engagementRate: 3.1,
    category: "MACRO",
    interests: ["Voyage", "Gastronomie", "Culture"],
    gender: "Femme",
    country: "France",
    languages: ["Français", "Anglais", "Espagnol"],
    ratePost: 3500,
    rateStory: 800,
    rateVideo: 6000,
    isVerified: true,
    isActive: true,
    subscription: "PRO",
    balance: 12300,
    userId: "user_inf_3",
  },
  {
    id: "inf_4",
    name: "Thomas Bernard",
    bio: "Tech enthusiast et gamer. Reviews honnêtes et contenu tech.",
    photo: "https://i.pravatar.cc/300?img=15",
    instagram: "@thomastech",
    youtube: "ThomasBernardTech",
    tiktok: "@thomastech",
    followers: 58000,
    engagementRate: 6.5,
    category: "MACRO",
    interests: ["Tech", "Gaming", "Innovation"],
    gender: "Homme",
    country: "France",
    languages: ["Français", "Anglais"],
    ratePost: 600,
    rateStory: 150,
    rateVideo: 1200,
    isVerified: false,
    isActive: true,
    subscription: "FREE",
    balance: 890,
    userId: "user_inf_4",
  },
  {
    id: "inf_5",
    name: "Camille Petit",
    bio: "Micro-influenceuse beauté naturelle et skincare. Authenticité avant tout.",
    photo: "https://i.pravatar.cc/300?img=44",
    instagram: "@camillepetit_beauty",
    tiktok: "@camillebeauty",
    followers: 8500,
    engagementRate: 8.9,
    category: "MICRO",
    interests: ["Beauté", "Skincare", "Bien-être"],
    gender: "Femme",
    country: "France",
    languages: ["Français"],
    ratePost: 150,
    rateStory: 50,
    rateVideo: 300,
    isVerified: false,
    isActive: true,
    subscription: "FREE",
    balance: 340,
    userId: "user_inf_5",
  },
  {
    id: "demo_inf",
    name: "Marie Dupont",
    bio: "Influenceuse lifestyle et mode. Basée à Paris.",
    photo: "https://i.pravatar.cc/300?img=25",
    instagram: "@mariedupont",
    tiktok: "@mariedupont",
    followers: 25000,
    engagementRate: 4.7,
    category: "MACRO",
    interests: ["Mode", "Lifestyle", "Beauté"],
    gender: "Femme",
    country: "France",
    languages: ["Français", "Anglais"],
    ratePost: 400,
    rateStory: 100,
    rateVideo: 800,
    isVerified: true,
    isActive: true,
    subscription: "PRO",
    balance: 1250,
    userId: "influencer-1",
  },
]

export const mockCampaigns = [
  {
    id: "camp_1",
    brandProfileId: "brand_1",
    brandName: "L'Oréal Paris",
    title: "Lancement Rouge à Lèvres Collection Automne",
    description: "Promotion de notre nouvelle collection de rouges à lèvres automne/hiver 2024.",
    budget: 15000,
    budgetRemaining: 8500,
    startDate: "2024-09-01",
    endDate: "2024-11-30",
    targetGender: "Femme",
    targetInterests: ["Beauté", "Mode", "Lifestyle"],
    targetCountries: ["France"],
    targetLanguages: ["Français"],
    targetCategory: "MACRO",
    status: "ACTIVE",
    promoCode: "LOREAL20",
    websiteUrl: "https://loreal.fr",
    autoAssign: false,
    influencersCount: 5,
    createdAt: "2024-08-15",
  },
  {
    id: "camp_2",
    brandProfileId: "brand_2",
    brandName: "Nike France",
    title: "Campagne Running Hiver 2024",
    description: "Mise en avant de notre nouvelle collection running pour l'hiver.",
    budget: 25000,
    budgetRemaining: 15000,
    startDate: "2024-10-01",
    endDate: "2024-12-31",
    targetGender: null,
    targetInterests: ["Sport", "Fitness", "Running"],
    targetCountries: ["France", "Belgique"],
    targetLanguages: ["Français"],
    targetCategory: "MACRO",
    status: "ACTIVE",
    promoCode: "NIKE15",
    websiteUrl: "https://nike.fr",
    autoAssign: true,
    influencersCount: 8,
    createdAt: "2024-09-20",
  },
  {
    id: "camp_3",
    brandProfileId: "brand-1",
    brandName: "Maison Élégance",
    title: "Campagne Mode Automne",
    description: "Campagne de mise en avant de notre collection automne.",
    budget: 5000,
    budgetRemaining: 3200,
    startDate: "2024-10-15",
    endDate: "2024-12-15",
    targetGender: "Femme",
    targetInterests: ["Mode", "Lifestyle"],
    targetCountries: ["France"],
    targetLanguages: ["Français"],
    targetCategory: "MICRO",
    status: "ACTIVE",
    promoCode: "MAISON10",
    websiteUrl: "https://maison-elegance.fr",
    autoAssign: false,
    influencersCount: 3,
    createdAt: "2024-10-01",
  },
]

export const mockTransactions = [
  {
    id: "tx_1",
    userId: "brand-1",
    type: "DEPOSIT",
    amount: 5000,
    description: "Rechargement portefeuille",
    createdAt: "2024-10-01",
  },
  {
    id: "tx_2",
    userId: "brand-1",
    type: "CAMPAIGN_PAYMENT",
    amount: -1800,
    description: "Paiement campagne: Campagne Mode Automne",
    createdAt: "2024-10-15",
  },
  {
    id: "tx_3",
    userId: "influencer-1",
    type: "CAMPAIGN_PAYMENT",
    amount: 400,
    description: "Rémunération campagne: Campagne Mode Automne",
    createdAt: "2024-10-20",
  },
  {
    id: "tx_4",
    userId: "influencer-1",
    type: "WITHDRAWAL",
    amount: -200,
    description: "Virement bancaire",
    createdAt: "2024-10-25",
  },
]

export const mockProposals = [
  {
    id: "prop_1",
    campaignId: "camp_1",
    campaignTitle: "Lancement Rouge à Lèvres Collection Automne",
    brandName: "L'Oréal Paris",
    payment: 800,
    status: "PENDING",
    createdAt: "2024-10-15",
    description: "Nous recherchons des créateurs de contenu beauté pour promouvoir notre nouvelle collection.",
  },
  {
    id: "prop_2",
    campaignId: "camp_2",
    campaignTitle: "Campagne Running Hiver 2024",
    brandName: "Nike France",
    payment: 400,
    status: "ACCEPTED",
    createdAt: "2024-10-10",
    description: "Rejoignez notre campagne running pour présenter notre nouvelle collection hiver.",
  },
]

export const mockMissions = [
  {
    id: "miss_1",
    campaignId: "camp_3",
    campaignTitle: "Campagne Mode Automne",
    brandName: "Maison Élégance",
    payment: 400,
    status: "ACCEPTED",
    deadline: "2024-12-01",
    instructions: "Créer un post Instagram et 2 stories présentant nos produits avec le code MAISON10.",
    postUrl: null,
    createdAt: "2024-10-15",
  },
]

export const mockBrands = [
  {
    id: "brand_1",
    companyName: "L'Oréal Paris",
    logo: "https://picsum.photos/seed/loreal/100/100",
    website: "https://loreal.fr",
    description: "Leader mondial de la beauté",
    balance: 45000,
    campaignsCount: 12,
    userId: "user_brand_1",
  },
  {
    id: "brand_2",
    companyName: "Nike France",
    logo: "https://picsum.photos/seed/nike/100/100",
    website: "https://nike.fr",
    description: "Just Do It",
    balance: 125000,
    campaignsCount: 8,
    userId: "user_brand_2",
  },
  {
    id: "brand-1",
    companyName: "Maison Élégance",
    logo: null,
    website: "https://maison-elegance.fr",
    description: "Mode et élégance française",
    balance: 3200,
    campaignsCount: 1,
    userId: "brand-1",
  },
]

export const DEMO_USERS = {
  admin: {
    id: "admin-1",
    email: "admin@dotthetalents.com",
    password: "admin123",
    role: "ADMIN",
    name: "Administrateur",
  },
  brand: {
    id: "brand-1",
    email: "marque@demo.com",
    password: "demo123",
    role: "BRAND",
    name: "Maison Élégance",
    brandProfileId: "brand-1",
  },
  influencer: {
    id: "influencer-1",
    email: "influenceur@demo.com",
    password: "demo123",
    role: "INFLUENCER",
    name: "Sofia Martini",
    influencerProfileId: "demo_inf",
  },
}
